plugins { id 'com.android.application' }

android {
    namespace 'com.blazefm.blazesystems'
    compileSdk 35

    defaultConfig {
        applicationId 'com.blazefm.blazesystems'
        minSdk 21
        targetSdk 35
        versionCode 33
        versionName '1.3.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        resources {
            excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'commons-net:commons-net:3.11.1'
    implementation 'eu.agno3.jcifs:jcifs-ng:2.1.9'
    implementation 'org.slf4j:slf4j-nop:1.7.36'
    implementation 'com.github.mwiede:jsch:2.28.7'
}
