package com.blazefm.blazesystems;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.provider.OpenableColumns;
import android.widget.*;
import java.io.*;
import java.util.*;

public class CloudBrowserActivity extends Activity {
    static final int PICK_UPLOAD=702;
    static final class E{String id,name,mime;long size;boolean dir;}
    private Uri tree,current;private final ArrayDeque<Uri> stack=new ArrayDeque<>();private final ArrayList<E> entries=new ArrayList<>();private ListView list;private TextView path,status;
    @Override public void onCreate(Bundle b){super.onCreate(b);String s=getIntent().getStringExtra("tree");if(s==null){finish();return;}tree=Uri.parse(s);current=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));build();load();}
    private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);TextView h=Ui.text(this,"Cloud Browser",20);h.setTextColor(android.graphics.Color.WHITE);h.setBackgroundColor(Ui.ORANGE_DARK);r.addView(h);path=Ui.text(this,"",11);r.addView(path);LinearLayout bar=Ui.toolbar(this);Button up=Ui.button(this,"Up"),upload=Ui.button(this,"Upload"),folder=Ui.button(this,"New folder"),refresh=Ui.button(this,"Refresh");Ui.equalAdd(bar,up);Ui.equalAdd(bar,upload);Ui.equalAdd(bar,folder);Ui.equalAdd(bar,refresh);r.addView(bar);list=new ListView(this);r.addView(list,new LinearLayout.LayoutParams(-1,0,1));status=Ui.text(this,"",11);r.addView(status);setContentView(r);up.setOnClickListener(v->up());upload.setOnClickListener(v->pickUpload());folder.setOnClickListener(v->newFolder());refresh.setOnClickListener(v->load());list.setOnItemClickListener((p,v,pos,id)->open(entries.get(pos)));list.setOnItemLongClickListener((p,v,pos,id)->{menu(entries.get(pos));return true;});}
    private void load(){status.setText("Loading…");new Thread(()->{ArrayList<E>out=new ArrayList<>();try{String id=DocumentsContract.getDocumentId(current);Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,id);String[]pr={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE};try(Cursor c=getContentResolver().query(children,pr,null,null,null)){if(c!=null)while(c.moveToNext()){E e=new E();e.id=c.getString(0);e.name=c.getString(1);e.mime=c.getString(2);e.size=c.isNull(3)?0:c.getLong(3);e.dir=DocumentsContract.Document.MIME_TYPE_DIR.equals(e.mime);out.add(e);}}Collections.sort(out,(a,b)->{if(a.dir!=b.dir)return a.dir?-1:1;return a.name.compareToIgnoreCase(b.name);});runOnUiThread(()->{entries.clear();entries.addAll(out);String[]rows=new String[out.size()];for(int i=0;i<rows.length;i++){E e=out.get(i);rows[i]=(e.dir?"📁  ":"☁  ")+e.name+(e.dir?"":" · "+fmt(e.size));}list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,rows));path.setText(current.toString());status.setText(out.size()+" items");});}catch(Exception e){runOnUiThread(()->status.setText("Provider error: "+e.getMessage()));}}).start();}
    private Uri uri(E e){return DocumentsContract.buildDocumentUriUsingTree(tree,e.id);}
    private void open(E e){if(e.dir){stack.push(current);current=uri(e);load();}else{Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(uri(e),e.mime==null?"*/*":e.mime);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(i);}catch(Exception x){toast("No app can open this file");}}}
    private void menu(E e){String[]o=e.dir?new String[]{"Rename","Delete"}:new String[]{"Open","Save to Downloads","Rename","Delete"};new AlertDialog.Builder(this).setTitle(e.name).setItems(o,(d,w)->{if(!e.dir&&w==0)open(e);if(!e.dir&&w==1)download(e);int shift=e.dir?0:2;if(w==shift)rename(e);if(w==shift+1)delete(e);}).show();}
    private void download(E e){status.setText("Downloading…");new Thread(()->{try{File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"BlazeFM/Cloud");dir.mkdirs();File out=FileEngine.unique(dir,e.name);try(InputStream in=getContentResolver().openInputStream(uri(e));OutputStream o=new BufferedOutputStream(new FileOutputStream(out))){byte[]b=new byte[64*1024];int n;while(in!=null&&(n=in.read(b))!=-1)o.write(b,0,n);}runOnUiThread(()->status.setText("Saved: "+out.getAbsolutePath()));}catch(Exception x){runOnUiThread(()->toast("Save failed: "+x.getMessage()));}}).start();}
    private void rename(E e){EditText n=new EditText(this);n.setText(e.name);new AlertDialog.Builder(this).setTitle("Rename").setView(n).setPositiveButton("Rename",(d,w)->{try{DocumentsContract.renameDocument(getContentResolver(),uri(e),n.getText().toString().trim());load();}catch(Exception x){toast("Rename failed");}}).setNegativeButton("Cancel",null).show();}
    private void delete(E e){new AlertDialog.Builder(this).setTitle("Delete from provider?").setMessage(e.name).setPositiveButton("Delete",(d,w)->{try{DocumentsContract.deleteDocument(getContentResolver(),uri(e));load();}catch(Exception x){toast("Delete failed");}}).setNegativeButton("Cancel",null).show();}
    private void newFolder(){EditText n=new EditText(this);n.setHint("Folder name");new AlertDialog.Builder(this).setTitle("New folder").setView(n).setPositiveButton("Create",(d,w)->{try{DocumentsContract.createDocument(getContentResolver(),current,DocumentsContract.Document.MIME_TYPE_DIR,n.getText().toString().trim());load();}catch(Exception x){toast("Create failed");}}).setNegativeButton("Cancel",null).show();}
    private void pickUpload(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_UPLOAD);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==PICK_UPLOAD&&c==RESULT_OK&&data!=null&&data.getData()!=null)upload(data.getData());}
    private void upload(Uri src){status.setText("Uploading…");new Thread(()->{try{String name="upload.bin",mime=getContentResolver().getType(src);try(Cursor c=getContentResolver().query(src,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())name=c.getString(0);}Uri out=DocumentsContract.createDocument(getContentResolver(),current,mime==null?"application/octet-stream":mime,name);if(out==null)throw new IOException("Provider refused create");try(InputStream in=getContentResolver().openInputStream(src);OutputStream o=getContentResolver().openOutputStream(out)){byte[]b=new byte[64*1024];int n;while(in!=null&&o!=null&&(n=in.read(b))!=-1)o.write(b,0,n);}runOnUiThread(this::load);}catch(Exception e){runOnUiThread(()->toast("Upload failed: "+e.getMessage()));}}).start();}
    private void up(){if(!stack.isEmpty()){current=stack.pop();load();}else finish();}
    private String fmt(long n){String[]u={"B","KB","MB","GB"};double v=n;int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,"%.1f %s",v,u[i]);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onBackPressed(){up();}
}
