package com.blazefm.blazesystems;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private LinearLayout root,selectionBar; private ListView list; private TextView path,status,title;
    private File cwd; private final ArrayList<File>shown=new ArrayList<>(); private final LinkedHashSet<String>selected=new LinkedHashSet<>();
    private final ArrayList<File>clipboard=new ArrayList<>(); private boolean clipboardMove,cancel,showingResults; private final int REQ=9;

    @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();ensurePermission();cwd=Environment.getExternalStorageDirectory();showDir(cwd);}
    @Override public void onResume(){super.onResume();if(cwd!=null&&!showingResults)showDir(cwd);}

    private void buildUi(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);
        title=Ui.text(this,"BlazeFM",21);title.setTextColor(Color.WHITE);title.setBackgroundColor(Ui.ORANGE_DARK);title.setPadding(Ui.dp(this,16),Ui.dp(this,12),Ui.dp(this,16),Ui.dp(this,12));root.addView(title);
        path=Ui.text(this,"",11);path.setTextIsSelectable(true);root.addView(path);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout bar=Ui.toolbar(this);
        String[]bs={"↑ Up","⌂ Home","Paste","＋ New","Search","Tools"};for(String s:bs){Button b=Ui.button(this,s);bar.addView(b,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,44)));if(s.contains("Up"))b.setOnClickListener(v->up());else if(s.contains("Home"))b.setOnClickListener(v->showDir(Environment.getExternalStorageDirectory()));else if(s.equals("Paste"))b.setOnClickListener(v->paste());else if(s.contains("New"))b.setOnClickListener(v->createMenu());else if(s.equals("Search"))b.setOnClickListener(v->searchDialog());else b.setOnClickListener(v->tools());}hs.addView(bar);root.addView(hs);
        list=new ListView(this);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));
        selectionBar=Ui.toolbar(this);selectionBar.setVisibility(View.GONE);String[]ss={"Copy","Move","Zip","Trash","Clear"};for(String s:ss){Button b=Ui.button(this,s);Ui.equalAdd(selectionBar,b);if(s.equals("Copy"))b.setOnClickListener(v->prepareClipboard(false));if(s.equals("Move"))b.setOnClickListener(v->prepareClipboard(true));if(s.equals("Zip"))b.setOnClickListener(v->zipSelection());if(s.equals("Trash"))b.setOnClickListener(v->trashSelection());if(s.equals("Clear"))b.setOnClickListener(v->clearSelection());}root.addView(selectionBar);
        status=Ui.text(this,"Ready",11);status.setBackgroundColor(Color.WHITE);root.addView(status);setContentView(root);
        list.setOnItemClickListener((p,v,pos,id)->{File f=shown.get(pos);if(!selected.isEmpty()){toggleSelect(f);return;}if(f.isDirectory())showDir(f);else openFile(f);});
        list.setOnItemLongClickListener((p,v,pos,id)->{File f=shown.get(pos);if(!selected.isEmpty())toggleSelect(f);else fileMenu(f);return true;});
    }

    private void ensurePermission(){if(Build.VERSION.SDK_INT>=30&&!Environment.isExternalStorageManager()){new AlertDialog.Builder(this).setTitle("File access required").setMessage("BlazeFM is a full file manager. Android 11+ requires All files access for normal filesystem browsing, duplicates, archives and Trash. You can still use Cloud/SAF without it.").setPositiveButton("Open settings",(d,w)->{try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}).setNegativeButton("Later",null).show();}else if(Build.VERSION.SDK_INT>=23&&Build.VERSION.SDK_INT<30&&checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.WRITE_EXTERNAL_STORAGE},REQ);}

    private void showDir(File d){if(d==null||!d.isDirectory())return;showingResults=false;cwd=d;path.setText(d.getAbsolutePath());selected.clear();File[]a=null;try{a=d.listFiles();}catch(Exception ignored){}shown.clear();boolean hidden=AppPrefs.showHidden(this);if(a!=null){ArrayList<File>x=new ArrayList<>();for(File f:a)if((hidden||!f.getName().startsWith("."))&&!f.getName().equals(".BlazeFM_Trash"))x.add(f);Collections.sort(x,(u,v)->{if(u.isDirectory()!=v.isDirectory())return u.isDirectory()?-1:1;return u.getName().compareToIgnoreCase(v.getName());});shown.addAll(x);}render();status.setText(shown.size()+" items"+((clipboard.size()>0)?" · clipboard "+clipboard.size():""));}
    private void render(){String[]rows=new String[shown.size()];for(int i=0;i<rows.length;i++){File f=shown.get(i);boolean sel=selected.contains(AppPrefs.canon(f));String p=sel?"✓ ":(f.isDirectory()?"📁 ":icon(f));rows[i]=p+f.getName()+(f.isFile()?"   · "+fmt(f.length()):"");}list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,rows));selectionBar.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);title.setText(selected.isEmpty()?"BlazeFM":selected.size()+" selected");}
    private String icon(File f){if(FileEngine.isImage(f))return "🖼 ";if(FileEngine.isVideo(f))return "🎬 ";if(FileEngine.isAudio(f))return "🎵 ";if(FileEngine.isApk(f))return "🤖 ";if(FileEngine.isArchive(f))return "🗜 ";return "📄 ";}
    private void toggleSelect(File f){String k=AppPrefs.canon(f);if(!selected.remove(k))selected.add(k);render();}
    private void clearSelection(){selected.clear();render();}
    private List<File> selectedFiles(){ArrayList<File>a=new ArrayList<>();for(File f:shown)if(selected.contains(AppPrefs.canon(f)))a.add(f);return a;}
    private void up(){if(showingResults){showDir(cwd);return;}File p=cwd==null?null:cwd.getParentFile();if(p!=null)showDir(p);}

    private void openFile(File f){AppPrefs.addRecent(this,f);if(FileEngine.isImage(f)||FileEngine.isText(f)||FileEngine.isVideo(f)||FileEngine.isAudio(f)){Intent i=new Intent(this,PreviewActivity.class);i.putExtra("path",f.getAbsolutePath());startActivity(i);return;}Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(BlazeProvider.uriFor(f),FileEngine.mime(f));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(i);}catch(Exception e){toast("No app can open this file");}}

    private void fileMenu(File f){ArrayList<String>o=new ArrayList<>();o.add(f.isDirectory()?"Open":"Preview / Open");o.add(selected.contains(AppPrefs.canon(f))?"Unselect":"Select");o.add(AppPrefs.isFavorite(this,f)?"Remove favorite":"Add favorite");o.add("Copy");o.add("Move");o.add("Rename");if(f.isFile())o.add("Properties / SHA-256");if(FileEngine.isArchive(f))o.add("Extract ZIP here");if(FileEngine.isApk(f))o.add("APK info / Install");o.add("Move to Trash");o.add("Delete permanently");new AlertDialog.Builder(this).setTitle(f.getName()).setItems(o.toArray(new String[0]),(d,w)->{String s=o.get(w);if(s.startsWith("Open")||s.startsWith("Preview")){if(f.isDirectory())showDir(f);else openFile(f);}else if(s.endsWith("Select")||s.equals("Unselect"))toggleSelect(f);else if(s.contains("favorite")){AppPrefs.toggleFavorite(this,f);toast(AppPrefs.isFavorite(this,f)?"Added to favorites":"Removed from favorites");}else if(s.equals("Copy")){selected.clear();selected.add(AppPrefs.canon(f));prepareClipboard(false);}else if(s.equals("Move")){selected.clear();selected.add(AppPrefs.canon(f));prepareClipboard(true);}else if(s.equals("Rename"))rename(f);else if(s.startsWith("Properties"))hashDialog(f);else if(s.startsWith("Extract"))extract(f);else if(s.startsWith("APK"))apkInfo(f);else if(s.equals("Move to Trash"))trashOne(f);else if(s.startsWith("Delete permanently"))permanentDelete(f);}).show();}

    private void createMenu(){String[]o={"New folder","New empty text file"};new AlertDialog.Builder(this).setTitle("Create").setItems(o,(d,w)->{EditText e=new EditText(this);e.setHint(w==0?"Folder name":"File name.txt");new AlertDialog.Builder(this).setTitle(o[w]).setView(e).setPositiveButton("Create",(x,y)->{String n=e.getText().toString().trim();if(n.isEmpty()||n.contains("/")){toast("Invalid name");return;}try{File f=new File(cwd,n);boolean ok=w==0?f.mkdir():f.createNewFile();if(!ok)toast("Already exists or create failed");showDir(cwd);}catch(Exception z){toast("Create failed: "+z.getMessage());}}).setNegativeButton("Cancel",null).show();}).show();}
    private void rename(File f){EditText e=new EditText(this);e.setText(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setPositiveButton("Rename",(d,w)->{String n=e.getText().toString().trim();if(n.length()>0&&!n.contains("/")&&f.renameTo(new File(f.getParentFile(),n)))showDir(cwd);else toast("Rename failed or invalid name");}).setNegativeButton("Cancel",null).show();}

    private void prepareClipboard(boolean move){List<File>a=selectedFiles();if(a.isEmpty())return;clipboard.clear();clipboard.addAll(a);clipboardMove=move;clearSelection();status.setText((move?"Move":"Copy")+" clipboard: "+clipboard.size()+" · open destination and tap Paste");}
    private void paste(){if(clipboard.isEmpty()){toast("Clipboard is empty");return;}File dest=cwd;ArrayList<File>items=new ArrayList<>(clipboard);boolean move=clipboardMove;progress((move?"Moving":"Copying")+"…");new Thread(()->{int ok=0;for(File f:items){if(cancel)break;try{File out=FileEngine.unique(dest,f.getName());if(move)FileEngine.move(f,out);else FileEngine.copy(f,out);ok++;setProgress((move?"Move":"Copy")+": "+f.getName());}catch(Exception e){setProgress("Failed: "+f.getName()+" · "+e.getMessage());}}final int count=ok;runOnUiThread(()->{if(move){clipboard.clear();clipboardMove=false;}cancel=false;showDir(dest);status.setText(count+" item(s) completed");});}).start();}
    private void zipSelection(){List<File>a=selectedFiles();if(a.isEmpty())return;String ts=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(new Date());File out=FileEngine.unique(cwd,"BlazeFM-"+ts+".zip");progress("Creating ZIP…");new Thread(()->{try{FileEngine.zip(a,out);runOnUiThread(()->{clearSelection();showDir(cwd);status.setText("Created "+out.getName());});}catch(Exception e){runOnUiThread(()->toast("ZIP failed: "+e.getMessage()));}}).start();}
    private void extract(File zip){File dest=FileEngine.unique(cwd,stripExt(zip.getName()));dest.mkdirs();progress("Extracting "+zip.getName()+"…");new Thread(()->{try{FileEngine.unzip(zip,dest);runOnUiThread(()->{showDir(cwd);status.setText("Extracted to "+dest.getName());});}catch(Exception e){runOnUiThread(()->toast("Extract failed: "+e.getMessage()));}}).start();}
    private String stripExt(String n){int i=n.lastIndexOf('.');return i>0?n.substring(0,i):n+"_files";}

    private void trashOne(File f){new AlertDialog.Builder(this).setTitle("Move to Trash?").setMessage(f.getAbsolutePath()).setPositiveButton("Trash",(d,w)->new Thread(()->{try{TrashManager.moveToTrash(this,f);runOnUiThread(()->showDir(cwd));}catch(Exception e){runOnUiThread(()->toast("Trash failed: "+e.getMessage()));}}).start()).setNegativeButton("Cancel",null).show();}
    private void trashSelection(){List<File>a=selectedFiles();if(a.isEmpty())return;new AlertDialog.Builder(this).setTitle("Move selected to Trash?").setMessage(a.size()+" item(s) can be restored later.").setPositiveButton("Trash",(d,w)->new Thread(()->{for(File f:a)try{TrashManager.moveToTrash(this,f);}catch(Exception ignored){}runOnUiThread(()->{clearSelection();showDir(cwd);});}).start()).setNegativeButton("Cancel",null).show();}
    private void permanentDelete(File f){new AlertDialog.Builder(this).setTitle("Delete permanently?").setMessage(f.getAbsolutePath()+"\n\nThis cannot be restored from BlazeFM Trash.").setPositiveButton("DELETE",(d,w)->new Thread(()->{boolean ok=FileEngine.delete(f);runOnUiThread(()->{if(!ok)toast("Delete failed");showDir(cwd);});}).start()).setNegativeButton("Cancel",null).show();}

    private void searchDialog(){EditText e=new EditText(this);e.setHint("Filename contains…");new AlertDialog.Builder(this).setTitle("Search in "+cwd.getName()).setView(e).setPositiveButton("Search",(d,w)->runSearch(e.getText().toString())).setNegativeButton("Cancel",null).show();}
    private void runSearch(String q){if(q.trim().isEmpty())return;cancel=false;progress("Searching…");File base=cwd;new Thread(()->{List<File>a=FileEngine.walk(base,AppPrefs.showHidden(this),new P());ArrayList<File>r=new ArrayList<>();String needle=q.toLowerCase(Locale.US);for(File f:a)if(f.getName().toLowerCase(Locale.US).contains(needle))r.add(f);runOnUiThread(()->showResults("Search: "+q,r));}).start();}
    private void showResults(String t,List<File>r){showingResults=true;shown.clear();shown.addAll(r);selected.clear();String[]n=new String[r.size()];for(int i=0;i<n.length;i++)n[i]=r.get(i).getAbsolutePath();list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,n));path.setText(t+" · tap Up to return");status.setText(r.size()+" results");}

    private void scanDupes(){cancel=false;File base=cwd;progress("Finding exact duplicates…");new Thread(()->{try{List<FileEngine.DupGroup>g=FileEngine.exactDuplicates(base,AppPrefs.showHidden(this),new P());runOnUiThread(()->duplicateResults(g));}catch(Exception e){err(e);}}).start();}
    private void duplicateResults(List<FileEngine.DupGroup>g){long reclaim=0;StringBuilder b=new StringBuilder();for(FileEngine.DupGroup x:g){reclaim+=x.size*(x.files.size()-1L);b.append('\n').append(x.files.size()).append(" copies · ").append(fmt(x.size)).append(" each\n");for(File f:x.files)b.append(f.getAbsolutePath()).append('\n');}if(g.isEmpty())b.append("No exact duplicates found.");final long save=reclaim;new AlertDialog.Builder(this).setTitle("Exact duplicates · reclaimable "+fmt(save)).setMessage(b.toString()).setPositiveButton("Close",null).setNeutralButton(g.isEmpty()?"Close":"Trash extra copies",(d,w)->{if(!g.isEmpty())confirmDuplicateCleanup(g);}).show();status.setText("Duplicate scan complete");}
    private void confirmDuplicateCleanup(List<FileEngine.DupGroup>g){new AlertDialog.Builder(this).setTitle("Trash duplicate extras?").setMessage("BlazeFM will keep the first file in each SHA-256-verified group and move the other copies to Trash. Review the paths first.").setPositiveButton("Trash extras",(d,w)->new Thread(()->{int n=0;for(FileEngine.DupGroup x:g)for(int i=1;i<x.files.size();i++)try{TrashManager.moveToTrash(this,x.files.get(i));n++;}catch(Exception ignored){}final int z=n;runOnUiThread(()->{showDir(cwd);toast(z+" duplicate file(s) moved to Trash");});}).start()).setNegativeButton("Cancel",null).show();}
    private void scanPhotos(){cancel=false;File base=cwd;progress("Analyzing photos…");new Thread(()->{try{List<FileEngine.SimilarPair>p=FileEngine.similarPhotos(base,AppPrefs.showHidden(this),new P());runOnUiThread(()->photoResults(p));}catch(Exception e){err(e);}}).start();}
    private void photoResults(List<FileEngine.SimilarPair>p){StringBuilder b=new StringBuilder();int max=Math.min(p.size(),300);for(int i=0;i<max;i++){FileEngine.SimilarPair x=p.get(i);b.append("distance ").append(x.distance).append("\n").append(x.a.getAbsolutePath()).append("\n↔ ").append(x.b.getAbsolutePath()).append("\n\n");}if(p.isEmpty())b.append("No visually similar photo pairs found.");if(p.size()>max)b.append("… ").append(p.size()-max).append(" more pairs not shown");new AlertDialog.Builder(this).setTitle("Similar photos · "+p.size()+" pairs").setMessage(b.toString()).setPositiveButton("Close",null).show();status.setText("Photo scan complete");}

    private void tools(){String hidden=AppPrefs.showHidden(this)?"Hide hidden files":"Show hidden files";String[]o={"Exact duplicate finder","Similar photo finder","Storage analyzer","Favorites","Recent files","Trash / Recycle bin",hidden,"App manager / APK backup","Network: SMB / FTP / SFTP","Cloud / document providers","Root browser","Storage info","Refresh","About"};new AlertDialog.Builder(this).setTitle("BlazeFM Tools").setItems(o,(d,w)->{switch(w){case 0:scanDupes();break;case 1:scanPhotos();break;case 2:Intent a=new Intent(this,AnalyzerActivity.class);a.putExtra("path",cwd.getAbsolutePath());startActivity(a);break;case 3:showPaths("Favorites",AppPrefs.favorites(this));break;case 4:showPaths("Recent files",AppPrefs.recents(this));break;case 5:trashDialog();break;case 6:AppPrefs.setShowHidden(this,!AppPrefs.showHidden(this));showDir(cwd);break;case 7:startActivity(new Intent(this,AppManagerActivity.class));break;case 8:startActivity(new Intent(this,RemoteActivity.class));break;case 9:startActivity(new Intent(this,CloudActivity.class));break;case 10:startActivity(new Intent(this,RootActivity.class));break;case 11:storageInfo();break;case 12:showDir(cwd);break;case 13:about();break;}}).show();}
    private void showPaths(String t,Collection<String>paths){ArrayList<String>a=new ArrayList<>();for(String p:paths)if(new File(p).exists())a.add(p);if(a.isEmpty()){toast("No saved items");return;}new AlertDialog.Builder(this).setTitle(t).setItems(a.toArray(new String[0]),(d,w)->{File f=new File(a.get(w));if(f.isDirectory())showDir(f);else openFile(f);}).setPositiveButton("Close",null).show();}
    private void trashDialog(){List<TrashManager.Item>a=TrashManager.list(this);if(a.isEmpty()){toast("Trash is empty");return;}String[]rows=new String[a.size()];for(int i=0;i<rows.length;i++)rows[i]=a.get(i).stored.getName()+"\nfrom: "+a.get(i).original;new AlertDialog.Builder(this).setTitle("Trash · "+a.size()+" items").setItems(rows,(d,w)->trashItem(a.get(w))).setNeutralButton("Empty Trash",(d,w)->new AlertDialog.Builder(this).setTitle("Empty Trash permanently?").setPositiveButton("Empty",(x,y)->new Thread(()->{TrashManager.empty(this);runOnUiThread(()->toast("Trash emptied"));}).start()).setNegativeButton("Cancel",null).show()).setPositiveButton("Close",null).show();}
    private void trashItem(TrashManager.Item i){String[]o={"Restore","Delete permanently"};new AlertDialog.Builder(this).setTitle(i.stored.getName()).setMessage("Original: "+i.original).setItems(o,(d,w)->{if(w==0)new Thread(()->{try{File r=TrashManager.restore(this,i);runOnUiThread(()->toast("Restored: "+r.getAbsolutePath()));}catch(Exception e){runOnUiThread(()->toast("Restore failed: "+e.getMessage()));}}).start();else new Thread(()->{TrashManager.purge(this,i);runOnUiThread(()->toast("Deleted permanently"));}).start();}).show();}

    private void hashDialog(File f){progress("Hashing…");new Thread(()->{try{String h=FileEngine.sha256(f);String msg="Path: "+f.getAbsolutePath()+"\nSize: "+fmt(f.length())+"\nModified: "+new Date(f.lastModified())+"\nMIME: "+FileEngine.mime(f)+"\n\nSHA-256\n"+h;runOnUiThread(()->new AlertDialog.Builder(this).setTitle(f.getName()).setMessage(msg).setPositiveButton("OK",null).show());}catch(Exception e){err(e);}}).start();}
    private void apkInfo(File f){PackageManager pm=getPackageManager();PackageInfo pi=pm.getPackageArchiveInfo(f.getAbsolutePath(),PackageManager.GET_ACTIVITIES);String msg;if(pi==null)msg="Unable to parse APK.";else{ApplicationInfo ai=pi.applicationInfo;if(ai!=null){ai.sourceDir=f.getAbsolutePath();ai.publicSourceDir=f.getAbsolutePath();}String label=ai==null?f.getName():String.valueOf(pm.getApplicationLabel(ai));msg=label+"\nPackage: "+pi.packageName+"\nVersion: "+pi.versionName+" ("+(Build.VERSION.SDK_INT>=28?pi.getLongVersionCode():pi.versionCode)+")\nSize: "+fmt(f.length());}new AlertDialog.Builder(this).setTitle("APK").setMessage(msg).setPositiveButton("Install",(d,w)->installApk(f)).setNegativeButton("Close",null).show();}
    private void installApk(File f){Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(BlazeProvider.uriFor(f),"application/vnd.android.package-archive");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);try{startActivity(i);}catch(Exception e){toast("Installer unavailable. Allow 'Install unknown apps' for BlazeFM if prompted.");}}

    private void storageInfo(){File e=Environment.getExternalStorageDirectory();long total=e.getTotalSpace(),free=e.getFreeSpace();new AlertDialog.Builder(this).setTitle("Storage").setMessage("Total: "+fmt(total)+"\nUsed: "+fmt(total-free)+"\nFree: "+fmt(free)+"\n\nCurrent folder:\n"+cwd.getAbsolutePath()).setPositiveButton("OK",null).show();}
    private void about(){String m="BlazeFM 1.1.0\ncom.blazefm.blazesystems\nAndroid 5.0+ (API 21)\n\nLocal file manager, batch copy/move, ZIP, Trash, hidden files, favorites/recent, exact SHA-256 duplicates, similar photos, analyzer, APK manager/backup, media/text preview, SAF cloud providers, SMB/FTP/SFTP, and optional root browser.\n\nNo ads or analytics.";new AlertDialog.Builder(this).setTitle("About BlazeFM").setMessage(m).setPositiveButton("OK",null).show();}

    private void progress(String s){cancel=false;status.setText(s+" · tap status to cancel");status.setOnClickListener(v->{cancel=true;status.setText("Cancelling…");});}
    private void setProgress(String s){runOnUiThread(()->status.setText(s));}
    private class P implements FileEngine.Progress{public void update(String s,int d,int t){setProgress(s);}public boolean cancelled(){return cancel;}}
    private void err(Exception e){runOnUiThread(()->{status.setText("Error");new AlertDialog.Builder(this).setTitle("Operation failed").setMessage(e.getClass().getSimpleName()+": "+e.getMessage()).setPositiveButton("OK",null).show();});}
    private String fmt(long n){String[]u={"B","KB","MB","GB","TB"};double v=n;int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,v>=10?"%.0f %s":"%.1f %s",v,u[i]);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override public void onBackPressed(){if(!selected.isEmpty()){clearSelection();return;}if(showingResults){showDir(cwd);return;}File home=Environment.getExternalStorageDirectory();if(cwd!=null&&!cwd.equals(home)&&cwd.getParentFile()!=null)up();else super.onBackPressed();}
}
