package com.blazefm.blazesystems;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root,bar; ListView list; TextView path,status; File cwd; ArrayList<File> shown=new ArrayList<>(); volatile boolean cancel;
    int orange=Color.rgb(230,81,0); final int REQ=9;
    @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();ensurePermission();cwd=android.os.Environment.getExternalStorageDirectory();showDir(cwd);}
    @Override public void onResume(){super.onResume();if(cwd!=null)showDir(cwd);}
    TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.DKGRAY);v.setPadding(16,12,16,12);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(8,0,8,0);return b;}
    void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);TextView title=t("🔥 BlazeFM",20);title.setTextColor(Color.WHITE);title.setBackgroundColor(orange);root.addView(title,new LinearLayout.LayoutParams(-1,56));path=t("",12);root.addView(path);bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);String[] bs={"UP","HOME","SEARCH","DUPES","PHOTOS","MORE"};for(String s:bs){Button b=btn(s);bar.addView(b,new LinearLayout.LayoutParams(0,48,1));if(s.equals("UP"))b.setOnClickListener(v->up());if(s.equals("HOME"))b.setOnClickListener(v->showDir(android.os.Environment.getExternalStorageDirectory()));if(s.equals("SEARCH"))b.setOnClickListener(v->searchDialog());if(s.equals("DUPES"))b.setOnClickListener(v->scanDupes());if(s.equals("PHOTOS"))b.setOnClickListener(v->scanPhotos());if(s.equals("MORE"))b.setOnClickListener(v->more());}root.addView(bar);list=new ListView(this);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));status=t("Ready",11);root.addView(status);setContentView(root);list.setOnItemClickListener((p,v,pos,id)->{File f=shown.get(pos);if(f.isDirectory())showDir(f);else openFile(f);});list.setOnItemLongClickListener((p,v,pos,id)->{fileMenu(shown.get(pos));return true;});}
    void ensurePermission(){if(Build.VERSION.SDK_INT>=30&&!android.os.Environment.isExternalStorageManager()){try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION, Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}else if(Build.VERSION.SDK_INT>=23&&Build.VERSION.SDK_INT<30&&checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.WRITE_EXTERNAL_STORAGE},REQ);}
    void showDir(File d){if(d==null||!d.isDirectory())return;cwd=d;path.setText(d.getAbsolutePath());shown.clear();File[]a=null;try{a=d.listFiles();}catch(Exception ignored){}if(a!=null){Arrays.sort(a,(x,y)->{if(x.isDirectory()!=y.isDirectory())return x.isDirectory()?-1:1;return x.getName().compareToIgnoreCase(y.getName());});shown.addAll(Arrays.asList(a));}String[] names=new String[shown.size()];for(int i=0;i<names.length;i++){File f=shown.get(i);names[i]=(f.isDirectory()?"📁  ":"📄  ")+f.getName()+(f.isFile()?"   · "+fmt(f.length()):"");}list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,names));status.setText(shown.size()+" items");}
    void up(){File p=cwd==null?null:cwd.getParentFile();if(p!=null)showDir(p);}
    String fmt(long n){String[]u={"B","KB","MB","GB","TB"};double v=n;int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,v>=10?"%.0f %s":"%.1f %s",v,u[i]);}
    void openFile(File f){Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(BlazeProvider.uriFor(f),"*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(i);}catch(Exception e){toast("No app can open this file");}}
    void searchDialog(){final EditText e=new EditText(this);e.setHint("Filename contains…");new AlertDialog.Builder(this).setTitle("Search in "+cwd.getName()).setView(e).setPositiveButton("Search",(d,w)->runSearch(e.getText().toString())).setNegativeButton("Cancel",null).show();}
    void runSearch(String q){if(q.trim().isEmpty())return;cancel=false;progress("Searching…");new Thread(()->{List<File>a=FileEngine.walk(cwd,new P());ArrayList<File>r=new ArrayList<>();for(File f:a)if(f.getName().toLowerCase().contains(q.toLowerCase()))r.add(f);runOnUiThread(()->showResults("Search: "+q,r));}).start();}
    void scanDupes(){cancel=false;progress("Finding exact duplicates…");new Thread(()->{try{List<FileEngine.DupGroup>g=FileEngine.exactDuplicates(cwd,new P());runOnUiThread(()->duplicateResults(g));}catch(Exception e){err(e);}}).start();}
    void duplicateResults(List<FileEngine.DupGroup> g){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);long reclaim=0;for(FileEngine.DupGroup x:g){reclaim+=x.size*(x.files.size()-1L);TextView h=t(x.files.size()+" copies · "+fmt(x.size)+" each",15);h.setTextColor(orange);box.addView(h);for(File f:x.files)box.addView(t(f.getAbsolutePath(),11));}if(g.isEmpty())box.addView(t("No exact duplicates found.",15));ScrollView s=new ScrollView(this);s.addView(box);new AlertDialog.Builder(this).setTitle("Exact duplicates · reclaimable "+fmt(reclaim)).setView(s).setPositiveButton("Close",null).show();status.setText("Duplicate scan complete");}
    void scanPhotos(){cancel=false;progress("Analyzing photos…");new Thread(()->{List<File>a=FileEngine.walk(cwd,new P());ArrayList<File>im=new ArrayList<>();ArrayList<Long>hs=new ArrayList<>();for(File f:a)if(FileEngine.isImage(f)&&!cancel){long h=FileEngine.dHash(f);if(h!=Long.MIN_VALUE){im.add(f);hs.add(h);}}ArrayList<String>pairs=new ArrayList<>();for(int i=0;i<im.size();i++)for(int j=i+1;j<im.size();j++)if(FileEngine.hamming(hs.get(i),hs.get(j))<=6)pairs.add(im.get(i).getAbsolutePath()+"\n↔ "+im.get(j).getAbsolutePath());runOnUiThread(()->photoResults(pairs));}).start();}
    void photoResults(List<String> p){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);for(String s:p)b.addView(t(s,11));if(p.isEmpty())b.addView(t("No visually similar photo pairs found.",15));ScrollView sc=new ScrollView(this);sc.addView(b);new AlertDialog.Builder(this).setTitle("Similar photos · "+p.size()+" pairs").setView(sc).setPositiveButton("Close",null).show();status.setText("Photo scan complete");}
    void showResults(String title,List<File> r){shown.clear();shown.addAll(r);String[]n=new String[r.size()];for(int i=0;i<n.length;i++)n[i]=r.get(i).getAbsolutePath();list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,n));path.setText(title);status.setText(r.size()+" results");}
    void progress(String s){status.setText(s+"  (tap status to cancel)");status.setOnClickListener(v->{cancel=true;status.setText("Cancelling…");});}
    class P implements FileEngine.Progress{public void update(String s,int d,int t){runOnUiThread(()->status.setText(s));}public boolean cancelled(){return cancel;}}
    void fileMenu(File f){String[]o={"Properties / SHA-256","Rename","Delete"};new AlertDialog.Builder(this).setTitle(f.getName()).setItems(o,(d,w)->{if(w==0)hashDialog(f);if(w==1)rename(f);if(w==2)confirmDelete(f);}).show();}
    void hashDialog(File f){progress("Hashing…");new Thread(()->{try{String h=FileEngine.sha256(f);runOnUiThread(()->new AlertDialog.Builder(this).setTitle("SHA-256").setMessage(h+"\n\n"+f.getAbsolutePath()).setPositiveButton("OK",null).show());}catch(Exception e){err(e);}}).start();}
    void rename(File f){EditText e=new EditText(this);e.setText(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setPositiveButton("Rename",(d,w)->{String n=e.getText().toString().trim();if(n.length()>0&&!n.contains("/")&&f.renameTo(new File(f.getParentFile(),n)))showDir(cwd);else toast("Rename failed or invalid name");}).setNegativeButton("Cancel",null).show();}
    void confirmDelete(File f){new AlertDialog.Builder(this).setTitle("Delete?").setMessage(f.getAbsolutePath()+"\n\nThis cannot be undone by BlazeFM.").setPositiveButton("DELETE",(d,w)->{if(FileEngine.delete(f))showDir(cwd);else toast("Delete failed");}).setNegativeButton("Cancel",null).show();}
    void more(){String[]o={"Refresh","Storage info","About"};new AlertDialog.Builder(this).setTitle("Tools").setItems(o,(d,w)->{if(w==0)showDir(cwd);if(w==1)storageInfo();if(w==2)new AlertDialog.Builder(this).setTitle("BlazeFM 1.0.1").setMessage("Compact native file manager\nPackage: com.blazefm.blazesystems\nMinimum: Android 5.0 (API 21)\nExact duplicates: SHA-256 verified\nSimilar photos: perceptual dHash").setPositiveButton("OK",null).show();}).show();}
    void storageInfo(){File e=android.os.Environment.getExternalStorageDirectory();long total=e.getTotalSpace(),free=e.getFreeSpace();new AlertDialog.Builder(this).setTitle("Storage").setMessage("Total: "+fmt(total)+"\nUsed: "+fmt(total-free)+"\nFree: "+fmt(free)).setPositiveButton("OK",null).show();}
    void err(Exception e){runOnUiThread(()->{status.setText("Error");new AlertDialog.Builder(this).setTitle("Operation failed").setMessage(e.getClass().getSimpleName()+": "+e.getMessage()).setPositiveButton("OK",null).show();});}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onBackPressed(){File home=android.os.Environment.getExternalStorageDirectory();if(cwd!=null&&!cwd.equals(home)&&cwd.getParentFile()!=null)up();else super.onBackPressed();}
}
