package com.blazefm.blazesystems;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.text.InputType;
import android.view.View;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class RemoteActivity extends Activity {
    private static final int PICK=703;
    private Spinner proto;private EditText host,port,user,pass,share,domain,start;private LinearLayout connectBox,browserBox;private ListView list;private TextView path,status;private final ArrayList<RemoteSession.Entry>entries=new ArrayList<>();private final ExecutorService exec=Executors.newSingleThreadExecutor();private RemoteSession session;private String cwd="/";
    @Override public void onCreate(Bundle b){super.onCreate(b);build();}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);return e;}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);TextView h=Ui.text(this,"Network · SMB / FTP / SFTP",20);h.setTextColor(android.graphics.Color.WHITE);h.setBackgroundColor(Ui.ORANGE_DARK);root.addView(h);connectBox=new LinearLayout(this);connectBox.setOrientation(LinearLayout.VERTICAL);connectBox.setPadding(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,8));proto=new Spinner(this);proto.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"SMB","FTP","SFTP"}));connectBox.addView(proto);host=field("Host / IP");port=field("Port (blank = default)");port.setInputType(InputType.TYPE_CLASS_NUMBER);user=field("Username");pass=field("Password");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);share=field("SMB share name");domain=field("SMB domain (optional)");start=field("Start path, e.g. /");connectBox.addView(host);connectBox.addView(port);connectBox.addView(user);connectBox.addView(pass);connectBox.addView(share);connectBox.addView(domain);connectBox.addView(start);Button connect=Ui.button(this,"Connect");connect.setOnClickListener(v->connect());connectBox.addView(connect);root.addView(connectBox);browserBox=new LinearLayout(this);browserBox.setOrientation(LinearLayout.VERTICAL);path=Ui.text(this,"/",11);browserBox.addView(path);LinearLayout bar=Ui.toolbar(this);Button up=Ui.button(this,"Up"),upload=Ui.button(this,"Upload"),folder=Ui.button(this,"New folder"),disc=Ui.button(this,"Disconnect");Ui.equalAdd(bar,up);Ui.equalAdd(bar,upload);Ui.equalAdd(bar,folder);Ui.equalAdd(bar,disc);browserBox.addView(bar);list=new ListView(this);browserBox.addView(list,new LinearLayout.LayoutParams(-1,0,1));status=Ui.text(this,"Disconnected",11);browserBox.addView(status);browserBox.setVisibility(View.GONE);root.addView(browserBox,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);up.setOnClickListener(v->up());upload.setOnClickListener(v->pick());folder.setOnClickListener(v->mkdir());disc.setOnClickListener(v->disconnect());list.setOnItemClickListener((p,v,pos,id)->open(entries.get(pos)));list.setOnItemLongClickListener((p,v,pos,id)->{menu(entries.get(pos));return true;});proto.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){boolean smb=pos==0;share.setVisibility(smb?View.VISIBLE:View.GONE);domain.setVisibility(smb?View.VISIBLE:View.GONE);}});}
    private void connect(){String pr=String.valueOf(proto.getSelectedItem());String h=host.getText().toString().trim();if(h.isEmpty()){toast("Enter a host");return;}int po=0;try{String x=port.getText().toString().trim();if(!x.isEmpty())po=Integer.parseInt(x);}catch(Exception ignored){}final int fp=po;status.setText("Connecting…");exec.execute(()->{try{RemoteSession s=RemoteFactory.connect(pr,h,fp,user.getText().toString(),pass.getText().toString(),share.getText().toString(),domain.getText().toString(),getFilesDir());session=s;String p=start.getText().toString().trim();cwd=p.isEmpty()?"/":p;runOnUiThread(()->{connectBox.setVisibility(View.GONE);browserBox.setVisibility(View.VISIBLE);load();});}catch(Exception e){runOnUiThread(()->toast("Connect failed: "+e.getMessage()));}});}
    private void load(){if(session==null)return;status.setText("Loading…");path.setText(cwd);exec.execute(()->{try{List<RemoteSession.Entry>a=session.list(cwd);runOnUiThread(()->{entries.clear();entries.addAll(a);String[]rows=new String[a.size()];for(int i=0;i<rows.length;i++){RemoteSession.Entry e=a.get(i);rows[i]=(e.dir?"📁  ":"🌐  ")+e.name+(e.dir?"":" · "+fmt(e.size));}list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,rows));status.setText(a.size()+" items");path.setText(cwd);});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+e.getMessage()));}});}
    private void open(RemoteSession.Entry e){if(e.dir){cwd=e.path;load();}else download(e);}
    private void menu(RemoteSession.Entry e){String[]o=e.dir?new String[]{"Open","Rename","Delete"}:new String[]{"Download","Rename","Delete"};new AlertDialog.Builder(this).setTitle(e.name).setItems(o,(d,w)->{if(w==0){if(e.dir){cwd=e.path;load();}else download(e);}if(w==1)rename(e);if(w==2)delete(e);}).show();}
    private void download(RemoteSession.Entry e){status.setText("Downloading "+e.name+"…");exec.execute(()->{try{File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"BlazeFM/Remote");dir.mkdirs();File out=FileEngine.unique(dir,e.name);try(OutputStream o=new BufferedOutputStream(new FileOutputStream(out))){session.download(e.path,o);}runOnUiThread(()->status.setText("Saved: "+out.getAbsolutePath()));}catch(Exception x){runOnUiThread(()->toast("Download failed: "+x.getMessage()));}});}
    private void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==PICK&&c==RESULT_OK&&data!=null&&data.getData()!=null)upload(data.getData());}
    private void upload(Uri u){status.setText("Uploading…");exec.execute(()->{try{String name="upload.bin";try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())name=c.getString(0);}String dst=RemoteFactory.join(cwd,name);try(InputStream in=getContentResolver().openInputStream(u)){if(in==null)throw new IOException("Cannot read selected file");session.upload(dst,in);}runOnUiThread(()->{status.setText("Upload complete");load();});}catch(Exception e){runOnUiThread(()->toast("Upload failed: "+e.getMessage()));}});}
    private void mkdir(){EditText e=field("Folder name");new AlertDialog.Builder(this).setTitle("New remote folder").setView(e).setPositiveButton("Create",(d,w)->exec.execute(()->{try{session.mkdir(RemoteFactory.join(cwd,e.getText().toString().trim()));runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->toast("Create failed: "+x.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    private void rename(RemoteSession.Entry e){EditText n=field("New name");n.setText(e.name);new AlertDialog.Builder(this).setTitle("Rename").setView(n).setPositiveButton("Rename",(d,w)->exec.execute(()->{try{session.rename(e.path,RemoteFactory.join(cwd,n.getText().toString().trim()));runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->toast("Rename failed: "+x.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    private void delete(RemoteSession.Entry e){new AlertDialog.Builder(this).setTitle("Delete remote item?").setMessage(e.name+(e.dir?"\nFolder must be empty.":"")).setPositiveButton("Delete",(d,w)->exec.execute(()->{try{session.delete(e.path,e.dir);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->toast("Delete failed: "+x.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    private void up(){if(session==null)return;String p=session.parent(cwd);if(p.equals(cwd)){return;}cwd=p;load();}
    private void disconnect(){try{if(session!=null)session.close();}catch(Exception ignored){}session=null;browserBox.setVisibility(View.GONE);connectBox.setVisibility(View.VISIBLE);status.setText("Disconnected");}
    private String fmt(long n){String[]u={"B","KB","MB","GB"};double v=n;int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,"%.1f %s",v,u[i]);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override protected void onDestroy(){disconnect();exec.shutdownNow();super.onDestroy();}
}
